name: Index Squash
on:
  schedule:
    - cron:  '45 16 * * *'
  workflow_dispatch:

jobs:
  squash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: crates.io-index-squash
    - uses: actions/checkout@v2
      with:
        repository: ehuss/crates.io-index
        path: crates.io-index
        fetch-depth: 0
        ssh-key: ${{ secrets.CRATES_IO_SSH_KEY }}
    - run: crates.io-index-squash/ci/squash.sh
